# Generated by Django 4.1.5 on 2023-05-11 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_alter_bookinstance_id_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e523124d-fab9-4e6a-b7dd-71185b5f9994'), help_text='Unique ID for this particular book accross the whole library', primary_key=True, serialize=False),
        ),
    ]
