# Generated by Django 4.1.5 on 2023-05-11 04:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_marked_returned', 'Set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b11b9101-1a9f-4513-b5b8-a3abc100980f'), help_text='Unique ID for this particular book accross the whole library', primary_key=True, serialize=False),
        ),
    ]
